name: .NET Build and Archive

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1'  # Specify your .NET version here

    - name: Restore dependencies
      run: dotnet restore ./GBRomViewer.sln
      
    - name: Build
      run: dotnet build --configuration Release --no-restore ./GBRomViewer.sln

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output ./publish ./GBRomViewer/GBRomViewer.csproj

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./publish/**
